CREATE TABLE `pacer_db`.`events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred` DATETIME NOT NULL,
  `action` VARCHAR(32) NOT NULL,
  `subject` VARCHAR(32) NOT NULL,
  `data` JSON NULL,
  `subject_id` INT UNSIGNED NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;